Repository MegEngine/Documentation, pull requests merged in 2021-09, with the labels that each got.

#242 add lite doc
  source/user-guide/deployment/lite/cpp.rst
  source/user-guide/deployment/lite/example.rst
  source/user-guide/deployment/lite/index.rst
  source/user-guide/deployment/lite/python.rst
  source/user-guide/deployment/lite/third-party.rst
  source/user-guide/index.rst
  source/user-guide/install/index.rst
Labels: documentation

#239 Change some details of the quick_start guide, which mainly includes t…
  source/getting-started/quick-start.ipynb
Labels: tutorial

#261 docs: add 404 page
  source/404.rst
  source/_static/images/404.png
  source/_templates/404.html
  source/conf.py
Labels: documentation

#255 docs(guide): add megengine.data user guide
  source/reference/data.rst
  source/user-guide/model-development/data/collator.rst
  source/user-guide/model-development/data/dataset.rst
  source/user-guide/model-development/data/index.rst
  source/user-guide/model-development/data/sampler.rst
  source/user-guide/model-development/data/transform.rst
Labels: documentation

#264 docs(explaination): add compnode explanation
  source/development/behind/compnode.rst
  source/development/behind/index.rst
Labels: documentation

#263 docs(tensor): add format documents (#262)
  source/_static/images/format_CHWN4.svg
  source/_static/images/format_NCHWX.svg
  source/_static/images/format_NCHW_NHWC.svg
  source/_static/images/format_logical_construction.svg
  source/user-guide/model-development/tensor/layout.rst
Labels: documentation

#274 docs(guide): add module guide
  .gitattributes
  source/_static/images/Simplified-illustration-of-the-AlexNet-architecture.pbm
  source/user-guide/model-development/module/design.rst
  source/user-guide/model-development/module/index.rst
Labels: documentation, user-guide

#275 docs(guide):add trace module user guide
  source/_static/images/tracemodule-flow.jpg
  source/user-guide/deployment/traced_module/api-example.rst
  source/user-guide/deployment/traced_module/design.rst
  source/user-guide/deployment/traced_module/graphsurgeon-example.rst
  source/user-guide/deployment/traced_module/index.rst
  source/user-guide/index.rst
Labels: documentation, user-guide
